openapi: 3.0.3
info:
  title: Training HUB
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8080
tags:
  - name: course
    description: Everything about the courses
paths:
  /getAllCourses:
    get:
      tags:
        - course
      summary: Gets all courses
      description: Gets all the courses in the database.
      operationId: getAllCourses
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /getCourseById/{courseId}:
    get:
      tags:
        - course
      summary: Get course by ID
      description: Retrieves a specific course by its ID.
      operationId: getCourseById
      parameters:
        - name: courseId
          in: path
          description: ID of the course to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /getCourseContent/{courseId}:
    get:
      tags:
        - course
      summary: Get course content by course ID
      description: Gets all the course content for a specific course.
      operationId: getCourseContent
      parameters:
        - name: courseId
          in: path
          description: ID of the course to retrieve content for
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'




components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        description:
          type: string
          example: Spring Boot crash course
        category:
          type: string
          description: Course Level
          enum:
            - Beginner
            - Intermediate
            - Professional
        instructorName:
          type: string
          example: Mr. John
        rating:
          type: integer
          format: int32
          example: 4
      xml:
        name: course

    Content:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 101
        course_id:
          type: integer
          format: int64
          example: 10
        topic_title:
          type: string
          example: Introduction to Spring Boot
        link:
          type: string
          format: uri
          example: https://example.com/spring-boot-intro
        duration:
          type: integer
          example: 120
      xml:
        name: content